Borrow/Models/Backend/Listing.cs
using Microsoft.EntityFrameworkCore;

namespace Borrow.Models.Backend
{
    public class Listing
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        [Precision(18, 2)]
        public decimal DailyRate { get; set; }
        [Precision(18, 2)]
        public decimal WeeklyRate { get; set; }
        public int OwnerId { get; set; }
        public int NeighborhoodId { get; set; }
        public bool Active { get; set; }
        public bool Dealt { get; set; }
    }
}

Borrow/Models/Listings/Item.cs
using Microsoft.EntityFrameworkCore;

namespace Borrow.Models.Listings
{
    public class Item
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime OwnedSince { get; set; }
        public int OwnerId { get; set; }
        public bool Available { get; set; }
        public bool IsListed { get; set; } = false;
        public int NeighborhoodId { get; set; }

        public Item()
        {
            Available = true;
        }

        public Item(int id, string name, string description, DateTime ownedSince, bool available, 
            decimal dailyRate, decimal weeklyRate, Guid identifier, bool isListed, string userName)
        {
            Id = id;
            Name = name;
            Description = description;
            OwnedSince = ownedSince;
            Available = available;
            IsListed = isListed;
        }

        internal void Unlist()
        {
            this.IsListed = false;
        }

        internal void List()
        {
            this.IsListed = true;
        }
    }
}

Borrow/Models/Views/Listing/CreateListingViewModel.cs
using AutoMapper;
using Borrow.Data.DataAccessLayer;
using Borrow.Models.Backend;
using Borrow.Models.Views.TableViews;

namespace Borrow.Models.Views.Listing
{
    public class CreateListingViewModel
    {
        public List<ItemViewModel> AvailableItems { get; set; }

        public CreateListingViewModel() { }

        public CreateListingViewModel(IEnumerable<Item> item)
        {
            AvailableItems = item.Select(i =>
            {
                return new ItemViewModel(i);
            }).ToList();
        }
    }
}

Borrow/Models/Views/Listing/PublishListingViewModel.cs
using Borrow.Models.Backend;
using Borrow.Models.Views.TableViews;

namespace Borrow.Models.Views.Listing
{
    public class PublishListingViewModel
    {
        public int NeighborhoodId { get; set; }
        public ItemViewModel ItemInfo { get; set; }
        public decimal DailyRate { get; set; }
        public decimal WeeklyRate { get; set; }
    }
}

Borrow/Models/Views/Listings/CreateListingViewModel.cs
using AutoMapper;
using Borrow.Data.Repositories;
using Borrow.Models.Backend;
using Borrow.Models.Views.TableViews;

namespace Borrow.Models.Views.Listings
{
    public class CreateListingViewModel
    {
        public List<ItemViewModel> AvailableItems { get; set; }

        public CreateListingViewModel() { }
    }
}

Borrow/Models/Views/Listings/PublishListingViewModel.cs
using Borrow.Models.Backend;
using Borrow.Models.Views.TableViews;

namespace Borrow.Models.Views.Listings
{
    public class PublishListingViewModel
    {
        public int NeighborhoodId { get; set; }
        public ItemViewModel ItemInfo { get; set; }
        public decimal DailyRate { get; set; }
        public decimal WeeklyRate { get; set; }
    }
}

Borrow/Models/Views/Listings/RemoveListingViewModel.cs
using Borrow.Models.Views.TableViews;

namespace Borrow.Models.Views.Listings
{
    public class RemoveListingViewModel
    {
        public List<SelectorViewModel<ListingViewModel>> Listings { get; set; }
    }
}

Borrow/Models/Views/NeighborhoodListingsViewModel.cs
using Borrow.Models.Views.TableViews;

namespace Borrow.Models.Views
{
    public class NeighborhoodListingsViewModel
    {
        public string Name { get; set; }
        public List<ListingViewModel> NeighborhoodListings { get; set; }

        public NeighborhoodListingsViewModel()
        {
            
        }
    }
}

Borrow/Models/Views/TableViews/ListingViewModel.cs
namespace Borrow.Models.Views.TableViews
{
    public class ListingViewModel
    {
        public int ListingId { get; set; }
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public decimal DailyRate { get; set; }
        public decimal WeeklyRate { get; set; }
        public string OwnerUsername { get; set; }
        public int OwnerId { get; set; }

        public ListingViewModel()
        {
                
        }

        public ListingViewModel(int id, int itemId, string item, string description, decimal dr, decimal wr, string owner, int ownerid)
        {
            ListingId = id;
            ItemId = itemId;
            ItemName = item;
            Description = description;
            DailyRate = dr;
            WeeklyRate = wr;
            OwnerUsername = owner;
            OwnerId = ownerid;
        }
    }
}

Borrow/Models/Views/UserListingsViewModel.cs
using AutoMapper;
using Borrow.Models.Backend;
using Borrow.Models.Views.TableViews;

namespace Borrow.Models.Views
{
    public class UserListingsViewModel
    {
        public List<ListingViewModel> ActiveListings { get; set; }

        public UserListingsViewModel()
        {
            
        }
    }
}

Borrow/Models/Views/ViewListingViewModel.cs
using AutoMapper;
using Borrow.Models.Backend;
using Borrow.Models.Views.TableViews;

namespace Borrow.Models.Views
{
    public class ViewListingViewModel
    {
        public ListingViewModel ListingViewModel { get; set; }

        public ViewListingViewModel()
        {

        }
    }
}

Borrow/Controllers/ListingsController.cs
using AutoMapper;
using Borrow.Data.Services;
using Borrow.Data.Services.Interfaces;
using Borrow.Models.Backend;
using Borrow.Models.Views.Listings;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Borrow.Controllers
{
    [Authorize]
    public class ListingsController : Controller
    {
        private readonly IProfileService _profileControllerService;
        private readonly IListingService _listingControllerService;

        public ListingsController(UserManager<User> um,
            IMapper mapper,
            IProfileService profileControllerService,
            IListingService controllerService)
        {
            _profileControllerService = profileControllerService;
            _listingControllerService = controllerService;
        }

        [HttpGet]
        public async Task<ActionResult> CreateListing()
        {
            var user = await _profileControllerService.GetCurrentUser(this.User);
            var clvm = _listingControllerService.GetCreateListingViewModel(user);
            return View(clvm);
        }

        [HttpGet]
        public async Task<ActionResult> PublishListing(int itemId)
        {
            var user = await _profileControllerService.GetCurrentUser(this.User);
            PublishListingViewModel p = _listingControllerService.GetPublishListingViewModel(itemId, user.ProfileId);
            return View(p);
        }

        [HttpPost]
        public async Task<ActionResult> PublishListing(PublishListingViewModel plvm)
        {
            _listingControllerService.CreateListing(plvm);
            return RedirectToAction("Index", "Profile");
        }

        [HttpGet]
        public async Task<ActionResult> RemoveListings()
        {
            var user = await _profileControllerService.GetCurrentUser(this.User);
            var listings = _listingControllerService.GetRemoveListingViewModel(user);
            return View(listings);
        }

        [HttpPost]
        public async Task<ActionResult> RemoveListings(RemoveListingViewModel rlvm)
        {
            var listingsToDeactive = rlvm.Listings.Where(l => l.IsSelected).ToList();
            _listingControllerService.DeactivateListing(listingsToDeactive.Select(l => l.Entity.ListingId));
            return RedirectToAction("Index", "Profile");
        }

        [HttpGet]
        public async Task<ActionResult> UserListings()
        {
            var user = await _profileControllerService.GetCurrentUser(this.User);
            var listings = _listingControllerService.GetUserListingsViewModel(user);
            return View(listings);
        }

        [HttpGet]
        public async Task<ActionResult> NeighborhoodListings()
        {
            var user = await _profileControllerService.GetCurrentUser(this.User);
            var listings = _listingControllerService.GetNeighborhoodListingsViewModel(user);

            return View(listings);
        }

        [HttpPost]
        public async Task<ActionResult> ViewListing(int listingId)
        {
            var vlvm = _listingControllerService.GetViewListingViewModel(listingId);
            return View(vlvm);
        }
    }
}

Borrow/Views/Listings/CreateListing.cshtml
@model Borrow.Models.Views.Listings.CreateListingViewModel
@{
    ViewBag.Title = "Publish Listing";
}

<h1>Select one of your items to list</h1>
<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<div class="row">
    <div>
        <table style="width:100%">
            <tr>
                <th>Item</th>
                <th>Description</th>
                <th></th>
            </tr>
            @for (int i = 0; i < Model.AvailableItems.Count(); ++i)
            {
                var item = Model.AvailableItems[i];
                <tr>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td>
                        @using (Html.BeginForm("PublishListing", "Listings", FormMethod.Get))
                        {
                            <button class="btn btn-primary" type="submit" name="itemId" value=@item.ItemId>List</button>
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

Borrow/Views/Listings/EditListings.cshtml
@model EditListingsViewModel

<div>
    @*<form>*@
        <div>
            <table style="width:100%">
                <tr>
                    <th>Item</th>
                    <th>Description</th>
                    <th>Owned Since</th>
                    <th>Available</th>
                    <th>Daily Rate</th>
                    <th>Weekly Rate</th>
                    <th></th>
                </tr>
                @for (int i = 0; i < Model.Items.Count(); ++i)
                {
                    var item = Model.Items[i];
                    <tr>
                        <td>
                            @item.Name
                        </td>
                        <td>
                            @item.Description
                        </td>
                        <td>
                            @item.OwnedSince
                        </td>
                        <td>
                            @item.Available
                        </td>
                        <td>
                            @item.DailyRate
                        </td>
                        <td>
                            @item.WeeklyRate
                        </td>
                        @if (item.IsListed)
                        {
                            <td>
                                @using(Html.BeginForm("Unlist", "Listings", FormMethod.Post))
                                {
                                    <button class="btn btn-primary" type="submit" name="unlistItem" value=@item.Identifier>Unlist</button>
                                }
                            </td>
                        }
                        else
                        {
                            <td>
                                @using (Html.BeginForm("List", "Listings", FormMethod.Post))
                                {
                                    <button class="btn btn-primary" type="submit" name="listItem" value=@item.Identifier>List</button>
                                }
                            </td>
                        }
                    </tr>
                }
            </table>
        </div>
    @*</form>*@
</div>

Borrow/Views/Listings/NeighborhoodListings.cshtml
@model NeighborhoodListingsViewModel

<div>
    <h1>@Model.Name Listings</h1>
    <div>
        <table style="width:100%">
            <tr>
                <th>Owner</th>
                <th>Item</th>
                <th>Description</th>
                <th>Daily Rate</th>
                <th>Weekly Rate</th>
                <th></th>
            </tr>
            @for (int i = 0; i < Model.NeighborhoodListings.Count(); ++i)
            {
                var item = Model.NeighborhoodListings[i];
                <tr>
                    <td>
                        @item.OwnerUsername
                    </td>
                    <td>
                        @item.ItemName
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td>
                        @item.DailyRate
                    </td>
                    <td>
                        @item.WeeklyRate
                    </td>
                    <td>
                        @using (Html.BeginForm("ViewListing", "Listings", FormMethod.Post))
                        {
                            <button class="btn btn-primary" type="submit" name="listingId" value=@item.ListingId>View Info</button>
                        }
                    </td>
                    
                </tr>
            }
        </table>
    </div>
</div>

Borrow/Views/Listings/PublishListing.cshtml
@model Borrow.Models.Views.Listings.PublishListingViewModel
@{
    ViewBag.Title = "Publish Listing";
}

<h1>Create your listing for @Model.ItemInfo.Name</h1>
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<form method="post" asp-action="PublishListing">
    <div class="form-group row">
        <div class="col-sm-2"><label>Daily Rate:</label></div>
        <div class="col-sm-4">
            <input asp-for="DailyRate" class="form-control" />
        </div>
        <div class="col">
            <span asp-validation-for="DailyRate"
                  class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-2"><label>Weekly Rate:</label></div>
        <div class="col-sm-4">
            <input asp-for="WeeklyRate" class="form-control" />
        </div>
        <div class="col">
            <span asp-validation-for="WeeklyRate"
                  class="text-danger"></span>
        </div>
    </div>
    @Html.HiddenFor(m=>m.ItemInfo.ItemId)
    @Html.HiddenFor(m=>m.NeighborhoodId)
    <div class="row">
        <div class="offset-2 col-sm-4">
            <button type="submit" class="btn btn-primary">Create</button>
        </div>
    </div>
    </div>
</form>

Borrow/Views/Listings/RemoveListing.cshtml
@model Borrow.Models.Views.Listings.RemoveListingViewModel

@{
    ViewData["Title"] = "RemoveListing";
}
<h1>Remove Your Listings</h1>

<h4>Please select the Listings you would like to remove and then click on submit</h4>
<hr />
<div class="row">
    <form method="post" asp-action="RemoveListing" asp-controller="Listings">
        <div>
            <table style="width:100%">
                <tr>
                    <th></th>
                    <th>Item</th>
                    <th>Description</th>
                    <th>Daily Rate</th>
                    <th>Weekly Rate</th>
                </tr>
                @for (int i = 0; i < Model.Listings.Count(); ++i)
                {
                    @Html.HiddenFor(m=>m.Listings[i].Entity.ListingId)
                    <tr>
                        <td>
                            @Html.CheckBoxFor(m=>m.Listings[i].IsSelected)
                        </td>
                        <td>
                            @Html.DisplayFor(m=>m.Listings[i].Entity.ItemName)
                        </td>
                        <td>
                            @Html.DisplayFor(m=>m.Listings[i].Entity.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(m=>m.Listings[i].Entity.DailyRate)
                        </td>
                        <td>
                            @Html.DisplayFor(m=>m.Listings[i].Entity.WeeklyRate)
                        </td>
                    </tr>
                }
            </table>
            <button class="btn btn-primary" type="submit" disabled="@(Model.Listings.Count() == 0)">Submit</button>
        </div>
    </form>
</div>

Borrow/Views/Listings/RemoveListings.cshtml
@model Borrow.Models.Views.Listings.RemoveListingViewModel

@{
    ViewData["Title"] = "RemoveListings";
}
<h1>Remove Your Listings</h1>

<h4>Please select the Listings you would like to remove and then click on submit</h4>
<hr />
<div class="row">
    <form method="post" asp-action="RemoveListings" asp-controller="Listings">
        <div>
            <table style="width:100%">
                <tr>
                    <th></th>
                    <th>Item</th>
                    <th>Description</th>
                    <th>Daily Rate</th>
                    <th>Weekly Rate</th>
                </tr>
                @for (int i = 0; i < Model.Listings.Count(); ++i)
                {
                    @Html.HiddenFor(m=>m.Listings[i].Entity.ListingId)
                    <tr>
                        <td>
                            @Html.CheckBoxFor(m=>m.Listings[i].IsSelected)
                        </td>
                        <td>
                            @Html.DisplayFor(m=>m.Listings[i].Entity.ItemName)
                        </td>
                        <td>
                            @Html.DisplayFor(m=>m.Listings[i].Entity.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(m=>m.Listings[i].Entity.DailyRate)
                        </td>
                        <td>
                            @Html.DisplayFor(m=>m.Listings[i].Entity.WeeklyRate)
                        </td>
                    </tr>
                }
            </table>
            <button class="btn btn-primary" type="submit" disabled="@(Model.Listings.Count() == 0)">Submit</button>
        </div>
    </form>
</div>

Borrow/Views/Listings/UserListings.cshtml
@model UserListingsViewModel

<div>
    <h1>Listed Items</h1>
    <div>
        <table style="width:100%">
            <tr>
                <th>Item</th>
                <th>Description</th>
                <th>Daily Rate</th>
                <th>Weekly Rate</th>
                <th>Owner</th>
                <th></th>
            </tr>
            @for (int i = 0; i < Model.ActiveListings.Count(); ++i)
            {
                var item = Model.ActiveListings[i];
                <tr>
                    <td>
                        @item.ItemName
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td>
                        @item.DailyRate
                    </td>
                    <td>
                        @item.WeeklyRate
                    </td>
                    <td>
                        @item.OwnerUsername
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

Borrow/Views/Listings/ViewListing.cshtml
@model ViewListingViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Listing Info</h1>
<div>
    <h4>@Model.ListingViewModel.ItemName</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ListingViewModel.OwnerUsername)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ListingViewModel.OwnerUsername)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ListingViewModel.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ListingViewModel.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ListingViewModel.DailyRate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ListingViewModel.DailyRate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ListingViewModel.WeeklyRate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ListingViewModel.WeeklyRate)
        </dd>
    </dl>
</div>
<a asp-action="NeighborhoodListings" asp-controller="Listings">
    <button class="btn btn-primary">Back</button>
</a>
@using (Html.BeginForm("SubmitRequestForListing", "Request", FormMethod.Get))
{
    <button class="btn btn-primary" type="submit" name="ListingId" value=@Model.ListingViewModel.ListingId>Request to Borrow!</button>
}
<hr />